#define A_HELP                   31897
#define L_HELP                     871
#define A_LOCATION               31885
#define L_LOCATION                  12
#define A_SPACE                  31884
#define L_SPACE                      1
#define A_LF                     31876
#define L_LF                         8
#define A_COMMA                  31874
#define L_COMMA                      2
#define A_PROMPT                 31872
#define L_PROMPT                     2
#define A_SURE                   31858
#define L_SURE                      14
#define A_QUIT                   31773
#define L_QUIT                      85
#define A_LOOK                   31751
#define L_LOOK                      22
#define A_DONTSEE                31725
#define L_DONTSEE                   26
#define A_CANTLOOK               31703
#define L_CANTLOOK                  22
#define A_CANTENTER              31673
#define L_CANTENTER                 30
#define A_CANTOPEN               31646
#define L_CANTOPEN                  27
#define A_NOTCARRYING            31613
#define L_NOTCARRYING               33
#define A_NOSUCHOBJECT           31593
#define L_NOSUCHOBJECT              20
#define A_NOSUCHPERSON           31573
#define L_NOSUCHPERSON              20
#define A_WHYTALK                31543
#define L_WHYTALK                   30
#define A_CANTUSE                31517
#define L_CANTUSE                   26
#define A_CANTREAD               31490
#define L_CANTREAD                  27
#define A_CANTUSEITEM            31451
#define L_CANTUSEITEM               39
#define A_RESPONSE               31433
#define L_RESPONSE                  18
#define A_INCORRECT              31356
#define L_INCORRECT                 77
#define A_CARRYTWO               31267
#define L_CARRYTWO                  89
#define A_ALREADYCARRYING        31230
#define L_ALREADYCARRYING           37
#define A_NOWCARRING             31208
#define L_NOWCARRING                22
#define A_EMPTYHANDS             31170
#define L_EMPTYHANDS                38
#define A_DROPPING               31154
#define L_DROPPING                  16
#define A_RETURNING              31093
#define L_RETURNING                 61
#define A_IDDQDMSG               31033
#define L_IDDQDMSG                  60
#define A_CONGRATS               30947
#define L_CONGRATS                  86
#define A_CANTGIVE               30907
#define L_CANTGIVE                  40
#define A_NOTPOSSIBLE            30880
#define L_NOTPOSSIBLE               27
#define A_ERROR                  30814
#define L_ERROR                     66
#define A_PRIEST                 30636
#define L_PRIEST                   178
#define A_PLEASEOFFER            30593
#define L_PLEASEOFFER               43
#define A_BADOFFERING            30532
#define L_BADOFFERING               61
#define A_YOURPART               30500
#define L_YOURPART                  32
#define A_IDLE                   30478
#define L_IDLE                      22
#define A_SALT                   30459
#define L_SALT                      19
#define A_HEXPREFIX              30457
#define L_HEXPREFIX                  2
#define A_DIGITS                 30441
#define L_DIGITS                    16
