#define A_HELP                   31897
#define L_HELP                     871
#define A_LOCATION               31885
#define L_LOCATION                  12
#define A_SPACE                  31884
#define L_SPACE                      1
#define A_LF                     31876
#define L_LF                         8
#define A_COMMA                  31874
#define L_COMMA                      2
#define A_PROMPT                 31872
#define L_PROMPT                     2
#define A_QUIT                   31787
#define L_QUIT                      85
#define A_LOOK                   31765
#define L_LOOK                      22
#define A_DONTSEE                31739
#define L_DONTSEE                   26
#define A_CANTLOOK               31717
#define L_CANTLOOK                  22
#define A_CANTENTER              31687
#define L_CANTENTER                 30
#define A_CANTOPEN               31660
#define L_CANTOPEN                  27
#define A_NOTCARRYING            31627
#define L_NOTCARRYING               33
#define A_NOSUCHOBJECT           31607
#define L_NOSUCHOBJECT              20
#define A_NOSUCHPERSON           31587
#define L_NOSUCHPERSON              20
#define A_WHYTALK                31557
#define L_WHYTALK                   30
#define A_CANTUSE                31531
#define L_CANTUSE                   26
#define A_CANTREAD               31504
#define L_CANTREAD                  27
#define A_CANTUSEITEM            31465
#define L_CANTUSEITEM               39
#define A_RESPONSE               31447
#define L_RESPONSE                  18
#define A_INCORRECT              31370
#define L_INCORRECT                 77
#define A_CARRYTWO               31281
#define L_CARRYTWO                  89
#define A_ALREADYCARRYING        31244
#define L_ALREADYCARRYING           37
#define A_NOWCARRING             31222
#define L_NOWCARRING                22
#define A_EMPTYHANDS             31184
#define L_EMPTYHANDS                38
#define A_DROPPING               31168
#define L_DROPPING                  16
#define A_RETURNING              31107
#define L_RETURNING                 61
#define A_IDDQDMSG               31047
#define L_IDDQDMSG                  60
#define A_CONGRATS               30961
#define L_CONGRATS                  86
#define A_CANTGIVE               30921
#define L_CANTGIVE                  40
#define A_NOTPOSSIBLE            30894
#define L_NOTPOSSIBLE               27
#define A_ERROR                  30828
#define L_ERROR                     66
#define A_PRIEST                 30650
#define L_PRIEST                   178
#define A_PLEASEOFFER            30607
#define L_PLEASEOFFER               43
#define A_BADOFFERING            30546
#define L_BADOFFERING               61
#define A_YOURPART               30514
#define L_YOURPART                  32
#define A_IDLE                   30492
#define L_IDLE                      22
#define A_SALT                   30473
#define L_SALT                      19
#define A_HEXPREFIX              30471
#define L_HEXPREFIX                  2
#define A_DIGITS                 30455
#define L_DIGITS                    16
